version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://user:password@db:3306/subscription_db
      - SECRET_KEY=your-secret-key-here
      - JWT_SECRET_KEY=your-jwt-secret-key-here
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=adminpassword
    volumes:
      - .:/app
    depends_on:
      - db
    command: /bin/sh -c "flask db upgrade && python -m app.init_admin && flask run --host=0.0.0.0"

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=subscription_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 